# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af860e9102f5b1eadba2a6c67a466fd2074d1ad63722b3eb55804216715a89d6824e25fb17358fbecd4cf298ba56255bb8f04b5e746395f86f04f37eebe6fcea

test:
  secret_key_base: e204c5abc0e9090946c93be38af6b0276f6857edd4dd888627605906d1b945ba6e5b828073dee0fc27748a8ca5f431be2f1c5e63a860861b669d0d278cc1c234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
